// This file is auto-generated by @hey-api/openapi-ts

export type AvatarRequest = {
    token: string;
    id: number;
};

export type DeleteReportRequest = {
    token: string;
    id: number;
};

export type Form = {
    name?: string;
    sex?: UserSex;
    birth?: string;
    phone?: string;
    email?: string;
    address?: string;
};

export type GetImageRequest = {
    token: string;
    id: number;
};

export type GetReportRequest = {
    token: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export  enum ImageType{
    source = 0,
    result = 1
}

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    code?: number;
    message?: string;
    token: (string | null);
};

export type RegisterRequest = {
    username: string;
    password: string;
    type: UserType;
};

export type ReportDetailRequest = {
    token: string;
    id: number;
};

export type ReportImageRequest = {
    token: string;
    id: number;
    type: ImageType;
};

export type ReportRequest = {
    token: string;
    doctor: string;
    images: Array<(number)>;
};

export type SubmitInfoRequest = {
    token: string;
    form: Form;
};

export type TokenRequest = {
    token: string;
};

export enum UserSex{
    Female = 0,
    Male = 1,
}

export enum UserType{
    Patient = 0,
    Doctor = 1
}
export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginApiLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiLoginPostResponse = (LoginResponse);

export type RegisterApiRegisterPostData = {
    requestBody: RegisterRequest;
};

export type RegisterApiRegisterPostResponse = (LoginResponse);

export type UserApiUserPostData = {
    requestBody: TokenRequest;
};

export type UserApiUserPostResponse = (unknown);

export type InfoApiInfoPostData = {
    requestBody: TokenRequest;
};

export type InfoApiInfoPostResponse = (unknown);

export type SubmitInfoApiSubmitInfoPostData = {
    requestBody: SubmitInfoRequest;
};

export type SubmitInfoApiSubmitInfoPostResponse = (unknown);

export type SubmitAvatarApiSubmitAvatarPostData = {
    requestBody: AvatarRequest;
};

export type SubmitAvatarApiSubmitAvatarPostResponse = (unknown);

export type AvatarApiAvatarPostData = {
    requestBody: TokenRequest;
};

export type AvatarApiAvatarPostResponse = (unknown);

export type SubmitReportApiSubmitReportPostData = {
    requestBody: ReportRequest;
};

export type SubmitReportApiSubmitReportPostResponse = (unknown);

export type GetReportsApiGetReportsPostData = {
    requestBody: GetReportRequest;
};

export type GetReportsApiGetReportsPostResponse = (unknown);

export type ReportImagesApiReportImagesPostData = {
    requestBody: ReportImageRequest;
};

export type ReportImagesApiReportImagesPostResponse = (unknown);

export type DeleteReportApiReportDeletePostData = {
    requestBody: DeleteReportRequest;
};

export type DeleteReportApiReportDeletePostResponse = (unknown);

export type GetReportDetailApiReportDetailPostData = {
    requestBody: ReportDetailRequest;
};

export type GetReportDetailApiReportDetailPostResponse = (unknown);

export type ImageApiImagePostResponse = (unknown);

export type GetImageApiImageGetPostData = {
    requestBody: GetImageRequest;
};

export type GetImageApiImageGetPostResponse = (unknown);

export type DoctorsApiDoctorsPostData = {
    requestBody: TokenRequest;
};

export type DoctorsApiDoctorsPostResponse = (unknown);

export type DoctorInfoApiDoctorInfoPostData = {
    requestBody: TokenRequest;
};

export type DoctorInfoApiDoctorInfoPostResponse = (unknown);